name: fluent_starter
description: A strict modular Flutter starter with Microsoft Fluent UI.
version: 0.1.0+1
publish_to: none
resolution: workspace
environment:
  sdk: ">=3.13.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  core_common: ^0.1.0
  core_data: ^0.1.0
  core_network: ^0.1.0
  core_design_system: ^0.1.0
  auth_domain: ^0.1.0
  auth_data: ^0.1.0
  auth_presentation: ^0.1.0
  home_presentation: ^0.1.0
  cupertino_icons: ^1.0.8
  auto_route: ^11.2.0
  fluent_ui: ^4.16.1
  flutter_bloc: ^9.1.1
  get_it: ^9.3.0
  injectable: ^3.0.0
  dio: ^5.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.0
  auto_route_generator: ^10.6.0
  injectable_generator: ^3.0.0
  flutter_flavorizr: ^2.6.0
  core_testing: ^0.1.0
flutter:
  uses-material-design: true
